/**
 * Compiles the deployed-page runtime (packages/export/src/runtime.ts) into the
 * inline script every exported page carries (packages/export/src/runtime.js.gen.ts).
 *
 *   node scripts/build-runtime.mjs          # write the generated module
 *   node scripts/build-runtime.mjs --check  # fail if it is stale
 *
 * Same shape as sync-export-css.mjs: the runtime is written as real TypeScript
 * so it is type-checked and linted like the rest of the package, and the
 * generated module is committed so consuming the package needs no build step.
 * A test asserts the two agree, so the pair cannot drift.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
export const repoRoot = resolve(here, '..');

const SOURCE = 'packages/export/src/runtime.ts';
const OUTPUT = 'packages/export/src/runtime.js.gen.ts';

/** Bundles the runtime into one self-contained IIFE for a browser. */
export const buildRuntimeJs = async (root = repoRoot) => {
  const result = await build({
    entryPoints: [resolve(root, SOURCE)],
    // Fixed, so the path comment esbuild writes does not depend on the caller's cwd.
    absWorkingDir: resolve(root),
    bundle: true,
    write: false,
    format: 'iife',
    // Wide enough for every browser that can render the page's CSS, narrow
    // enough that the output stays readable in View Source.
    target: ['es2019'],
    minify: false,
    legalComments: 'none',
    logLevel: 'silent',
  });
  const out = result.outputFiles[0];
  if (!out) throw new Error(`${SOURCE}: esbuild produced no output`);
  const js = out.text.trim();
  // The script is inlined into HTML, so a closing tag anywhere in it would end
  // the script element early and dump the rest of the runtime onto the page.
  if (/<\/script/i.test(js)) throw new Error(`${SOURCE}: output contains a closing script tag, which cannot be inlined`);
  return js;
};

export const renderModule = (js) =>
  `// Generated by scripts/build-runtime.mjs from ${SOURCE}. Do not edit by hand.\nexport const RUNTIME_JS: string = ${JSON.stringify(js)};\n`;

const main = async () => {
  const js = await buildRuntimeJs();
  const module_ = renderModule(js);
  const target = resolve(repoRoot, OUTPUT);
  if (process.argv.includes('--check')) {
    const current = readFileSync(target, 'utf8');
    if (current !== module_) {
      console.error(`${OUTPUT} is stale. Run: npm run build:runtime`);
      process.exit(1);
    }
    console.log(`${OUTPUT} is up to date (${(js.length / 1024).toFixed(1)} kb).`);
    return;
  }
  writeFileSync(target, module_, 'utf8');
  console.log(`Wrote ${OUTPUT} (${(js.length / 1024).toFixed(1)} kb of runtime).`);
};

if (process.argv[1] && resolve(process.argv[1]) === resolve(here, 'build-runtime.mjs')) await main();
